package ru.utils;

import lombok.Data;
import org.springframework.stereotype.Component;

import java.util.Map;

public class AsterParser {
    static final Map<String, Integer> DEFAULT_ASTER_INTERVALS = Map.ofEntries(
            // 8h intervals
            Map.entry("TSLA", 8), Map.entry("TRX", 8), Map.entry("QNTX", 8), Map.entry("DKNG", 8), Map.entry("BRKB", 8), Map.entry("APE", 8),
            Map.entry("MINIMAX", 8), Map.entry("AXTI", 8), Map.entry("BTC", 8), Map.entry("NOK", 8), Map.entry("HD", 8), Map.entry("JPM", 8),
            Map.entry("USAR", 8), Map.entry("AMD", 8), Map.entry("INTC", 8), Map.entry("AMAT", 8), Map.entry("ZM", 8), Map.entry("BX", 8),
            Map.entry("CRCL", 8), Map.entry("GALA", 8), Map.entry("AAPL", 8), Map.entry("GLW", 8), Map.entry("SOL", 8), Map.entry("CRV", 8),
            Map.entry("META", 8), Map.entry("DOT", 8), Map.entry("APT", 8), Map.entry("SEI", 8), Map.entry("ETHUSD1", 8), Map.entry("LLY", 8),
            Map.entry("HYUNDAI", 8), Map.entry("UBER", 8), Map.entry("ETH", 8), Map.entry("ARM", 8), Map.entry("MSTR", 8), Map.entry("SOLUSD1", 8),
            Map.entry("AAOI", 8), Map.entry("PAYP", 8), Map.entry("XIAOMI", 8), Map.entry("IREN", 8), Map.entry("MU", 8), Map.entry("CBRS", 8),
            Map.entry("EWY", 8), Map.entry("SUI", 8), Map.entry("BCH", 8), Map.entry("COST", 8), Map.entry("1000SHIB", 8), Map.entry("RIVN", 8),
            Map.entry("COHR", 8), Map.entry("AVAX", 8), Map.entry("UNI", 8), Map.entry("EBAY", 8), Map.entry("NBIS", 8), Map.entry("CRDO", 8),
            Map.entry("1000PEPE", 8), Map.entry("WDC", 8), Map.entry("ETHU", 8), Map.entry("POPMART", 8), Map.entry("ORCL", 8), Map.entry("V", 8),
            Map.entry("INJ", 8), Map.entry("BNB", 8), Map.entry("ETC", 8), Map.entry("AVGO", 8), Map.entry("DOGE", 8), Map.entry("ONDS", 8),
            Map.entry("XLM", 8), Map.entry("COIN", 8), Map.entry("SKHYNIX", 8), Map.entry("OP", 8), Map.entry("OPENAI", 8), Map.entry("BIRD", 8),
            Map.entry("LTC", 8), Map.entry("SOXL", 8), Map.entry("SAMSUNG", 8), Map.entry("NOW", 8), Map.entry("WMT", 8), Map.entry("RKLB", 8),
            Map.entry("PLTR", 8), Map.entry("ATOM", 8), Map.entry("LITE", 8), Map.entry("SNDK", 8), Map.entry("IBM", 8), Map.entry("QCOM", 8),
            Map.entry("NFLX", 8), Map.entry("CAR", 8), Map.entry("NVDA", 8), Map.entry("NVO", 8), Map.entry("MRVL", 8), Map.entry("XRP", 8),
            Map.entry("BE", 8), Map.entry("QQQ", 8), Map.entry("ASML", 8), Map.entry("USD1", 8), Map.entry("CRM", 8), Map.entry("SPCX", 8),
            Map.entry("DELL", 8), Map.entry("FUTU", 8), Map.entry("ADA", 8), Map.entry("CRWD", 8), Map.entry("ANTHROPIC", 8), Map.entry("DRAM", 8),
            Map.entry("MSFT", 8), Map.entry("GOOGL", 8), Map.entry("EWJ", 8), Map.entry("CRWV", 8), Map.entry("BBX", 8), Map.entry("LINK", 8),
            Map.entry("DIS", 8), Map.entry("ARB", 8), Map.entry("SPY", 8), Map.entry("AMZN", 8), Map.entry("GME", 8), Map.entry("IWM", 8),
            Map.entry("NEAR", 8), Map.entry("PDD", 8), Map.entry("AAVE", 8), Map.entry("BABA", 8), Map.entry("BTCUSD1", 8), Map.entry("ASTS", 8),
            Map.entry("URNM", 8), Map.entry("TSM", 8), Map.entry("1000FLOKI", 8), Map.entry("EWT", 8), Map.entry("TENCENT", 8), Map.entry("HOOD", 8),
            Map.entry("CSCO", 8), Map.entry("WLD", 8), Map.entry("DYDX", 8), Map.entry("FLNC", 8),

            // 4h intervals
            Map.entry("1000BONK", 4), Map.entry("SAPIEN", 4), Map.entry("OPEN", 4), Map.entry("ONDO", 4), Map.entry("TRADOOR", 4), Map.entry("HYPE", 4),
            Map.entry("TAG", 4), Map.entry("LISTA", 4), Map.entry("PUMP", 4), Map.entry("TRUMP", 4), Map.entry("LINEA", 4), Map.entry("NATGAS", 4),
            Map.entry("TAKE", 4), Map.entry("MOODENG", 4), Map.entry("XPIN", 4), Map.entry("TREE", 4), Map.entry("ZKC", 4), Map.entry("XAG", 4),
            Map.entry("B", 4), Map.entry("CL", 4), Map.entry("SPK", 4), Map.entry("CTR", 4), Map.entry("MITO", 4), Map.entry("AVNT", 4),
            Map.entry("C", 4), Map.entry("TON", 4), Map.entry("BZ", 4), Map.entry("TOSHI", 4), Map.entry("XPL", 4), Map.entry("NEIRO", 4),
            Map.entry("ZORA", 4), Map.entry("STBL", 4), Map.entry("TOWNS", 4), Map.entry("SAHARA", 4), Map.entry("FARTCOIN", 4), Map.entry("XPT", 4),
            Map.entry("HEMI", 4), Map.entry("XPD", 4), Map.entry("ENA", 4), Map.entry("FLOCK", 4), Map.entry("BTR", 4), Map.entry("PYTH", 4),
            Map.entry("AIO", 4), Map.entry("XAU", 4), Map.entry("PENGU", 4), Map.entry("PROVE", 4), Map.entry("XNY", 4), Map.entry("XCU", 4),
            Map.entry("PAXG", 4), Map.entry("IN", 4), Map.entry("BAS", 4), Map.entry("UB", 4), Map.entry("WLFI", 4), Map.entry("GENIUS", 4),
            Map.entry("SKY", 4), Map.entry("CAKE", 4), Map.entry("Q", 4), Map.entry("HOLO", 4), Map.entry("ASTER", 4), Map.entry("BLESS", 4),

            // 1h intervals
            Map.entry("SUSHI", 1), Map.entry("TRUTH", 1), Map.entry("BANK", 1), Map.entry("EVAA", 1), Map.entry("XAI", 1), Map.entry("SLX", 1),
            Map.entry("MON", 1), Map.entry("PNUT", 1), Map.entry("PENDLE", 1), Map.entry("DEXE", 1), Map.entry("AWE", 1), Map.entry("STAR", 1),
            Map.entry("SHELL", 1), Map.entry("NIGHT", 1), Map.entry("CHIP", 1), Map.entry("ESP", 1), Map.entry("GRIFFAIN", 1), Map.entry("MORPHO", 1),
            Map.entry("FHE", 1), Map.entry("CHILLGUY", 1), Map.entry("BROCCOLI714", 1), Map.entry("龙虾", 1), Map.entry("SOMI", 1), Map.entry("EUL", 1),
            Map.entry("HMSTR", 1), Map.entry("BREV", 1), Map.entry("POL", 1), Map.entry("OKB", 1), Map.entry("UMA", 1), Map.entry("AIOT", 1),
            Map.entry("B2", 1), Map.entry("ZEREBRO", 1), Map.entry("TROLL", 1), Map.entry("PLUME", 1), Map.entry("RECALL", 1), Map.entry("SKYAI", 1),
            Map.entry("VIRTUAL", 1), Map.entry("PROM", 1), Map.entry("G", 1), Map.entry("HUMA", 1), Map.entry("MANTRA", 1), Map.entry("TRB", 1),
            Map.entry("IP", 1), Map.entry("2Z", 1), Map.entry("PTB", 1), Map.entry("PIPPIN", 1), Map.entry("FORM", 1), Map.entry("KOMA", 1),
            Map.entry("HANA", 1), Map.entry("TA", 1), Map.entry("ENJ", 1), Map.entry("OPG", 1), Map.entry("ENS", 1), Map.entry("ASTEROID", 1),
            Map.entry("ZEC", 1), Map.entry("SYRUP", 1), Map.entry("MET", 1), Map.entry("PUMPBTC", 1), Map.entry("HOME", 1), Map.entry("STG", 1),
            Map.entry("STX", 1), Map.entry("GIGGLE", 1), Map.entry("STO", 1), Map.entry("1000WOJAK", 1), Map.entry("IO", 1), Map.entry("TAO", 1),
            Map.entry("TURTLE", 1), Map.entry("AR", 1), Map.entry("B3", 1), Map.entry("FIL", 1), Map.entry("FIDA", 1), Map.entry("BLEND", 1),
            Map.entry("AXL", 1), Map.entry("RONIN", 1), Map.entry("BTW", 1), Map.entry("1000SATS", 1), Map.entry("币安人生", 1), Map.entry("GMT", 1),
            Map.entry("PIEVERSE", 1), Map.entry("GWEI", 1), Map.entry("SPACE", 1), Map.entry("FLUX", 1), Map.entry("SKR", 1), Map.entry("RPL", 1),
            Map.entry("BLUAI", 1), Map.entry("ACX", 1), Map.entry("BIO", 1), Map.entry("RED", 1), Map.entry("O", 1), Map.entry("NOM", 1),
            Map.entry("FRAX", 1), Map.entry("MMT", 1), Map.entry("PRL", 1), Map.entry("RTX", 1), Map.entry("AVAAI", 1), Map.entry("ZRO", 1),
            Map.entry("XCN", 1), Map.entry("HYPER", 1), Map.entry("ETHFI", 1), Map.entry("M", 1), Map.entry("ORDI", 1), Map.entry("ALLO", 1),
            Map.entry("XAN", 1), Map.entry("SWARMS", 1), Map.entry("KGEN", 1), Map.entry("CFX", 1), Map.entry("FOLKS", 1), Map.entry("KAT", 1),
            Map.entry("ON", 1), Map.entry("COAI", 1), Map.entry("CLANKER", 1), Map.entry("UP", 1), Map.entry("RESOLV", 1), Map.entry("NOT", 1),
            Map.entry("COLLECT", 1), Map.entry("LUNA2", 1), Map.entry("IR", 1), Map.entry("ZBT", 1), Map.entry("MAGMA", 1), Map.entry("METIS", 1),
            Map.entry("MERL", 1), Map.entry("BIRB", 1), Map.entry("LAB", 1), Map.entry("GUN", 1), Map.entry("YB", 1), Map.entry("BOME", 1),
            Map.entry("BERA", 1), Map.entry("KAITO", 1), Map.entry("BEAT", 1), Map.entry("1000LUNC", 1), Map.entry("TURBO", 1), Map.entry("BABY", 1),
            Map.entry("PARTI", 1), Map.entry("JUP", 1), Map.entry("IRYS", 1), Map.entry("PENGUIN", 1), Map.entry("MOVR", 1), Map.entry("JCT", 1),
            Map.entry("INX", 1), Map.entry("TIA", 1), Map.entry("THETA", 1), Map.entry("ARKM", 1), Map.entry("BTCDOM", 1), Map.entry("AT", 1),
            Map.entry("FET", 1), Map.entry("BANANAS31", 1), Map.entry("ZEST", 1), Map.entry("CARDS", 1), Map.entry("AKE", 1), Map.entry("ZIL", 1),
            Map.entry("AXS", 1), Map.entry("BSB", 1), Map.entry("AGT", 1), Map.entry("CHZ", 1), Map.entry("KAS", 1), Map.entry("BAY", 1),
            Map.entry("FUN", 1), Map.entry("LUMIA", 1), Map.entry("EIGEN", 1), Map.entry("ENSO", 1), Map.entry("INIT", 1), Map.entry("SAGA", 1),
            Map.entry("1000NEX", 1), Map.entry("ARIA", 1), Map.entry("NIL", 1), Map.entry("HIGH", 1), Map.entry("D", 1), Map.entry("ZKP", 1),
            Map.entry("STABLE", 1), Map.entry("XMR", 1), Map.entry("ME", 1), Map.entry("CC", 1), Map.entry("ALICE", 1), Map.entry("AERO", 1),
            Map.entry("GPS", 1), Map.entry("STORJ", 1), Map.entry("SNX", 1), Map.entry("SOLV", 1), Map.entry("CFG", 1), Map.entry("S", 1),
            Map.entry("EDEN", 1), Map.entry("DASH", 1), Map.entry("JELLYJELLY", 1), Map.entry("PLAY", 1), Map.entry("DOGS", 1), Map.entry("COS", 1),
            Map.entry("USELESS", 1), Map.entry("RENDER", 1), Map.entry("TAC", 1), Map.entry("FLOW", 1), Map.entry("AEVO", 1), Map.entry("OGN", 1),
            Map.entry("MOVE", 1), Map.entry("AIA", 1), Map.entry("RAVE", 1), Map.entry("US", 1), Map.entry("KNC", 1), Map.entry("BLUR", 1),
            Map.entry("MEGA", 1), Map.entry("ESPORTS", 1), Map.entry("POWER", 1), Map.entry("TRUST", 1), Map.entry("SQD", 1), Map.entry("HBAR", 1),
            Map.entry("LIGHT", 1), Map.entry("POLYX", 1), Map.entry("VANA", 1), Map.entry("BAN", 1), Map.entry("EDU", 1), Map.entry("GTC", 1),
            Map.entry("ALGO", 1), Map.entry("LAYER", 1), Map.entry("BR", 1), Map.entry("SENT", 1), Map.entry("VVV", 1), Map.entry("ARPA", 1),
            Map.entry("VELO", 1), Map.entry("SIREN", 1), Map.entry("PIXEL", 1), Map.entry("STRK", 1), Map.entry("FOGO", 1), Map.entry("ARC", 1),
            Map.entry("DOOD", 1), Map.entry("LDO", 1), Map.entry("ORCA", 1), Map.entry("PORTAL", 1), Map.entry("4", 1), Map.entry("BEL", 1),
            Map.entry("DOLO", 1), Map.entry("PROMPT", 1), Map.entry("FIGHT", 1), Map.entry("AIGENSYN", 1), Map.entry("PHA", 1), Map.entry("ANIME", 1),
            Map.entry("API3", 1), Map.entry("ELSA", 1), Map.entry("CYS", 1), Map.entry("BULLA", 1), Map.entry("JTO", 1), Map.entry("TST", 1),
            Map.entry("LIT", 1), Map.entry("FF", 1), Map.entry("EDGE", 1), Map.entry("STEEM", 1), Map.entry("BMT", 1), Map.entry("LYN", 1),
            Map.entry("SOON", 1), Map.entry("TRIA", 1), Map.entry("WET", 1), Map.entry("ACU", 1), Map.entry("RAIL", 1), Map.entry("VELVET", 1),
            Map.entry("SAND", 1), Map.entry("RIF", 1), Map.entry("JASMY", 1), Map.entry("MELANIA", 1), Map.entry("YGG", 1), Map.entry("我踏马来了", 1),
            Map.entry("AVL", 1), Map.entry("NAORIS", 1), Map.entry("DYM", 1), Map.entry("ONT", 1), Map.entry("1000CHEEMS", 1), Map.entry("RIVER", 1),
            Map.entry("AUCTION", 1), Map.entry("ZK", 1), Map.entry("ALCH", 1), Map.entry("BB", 1), Map.entry("BARD", 1), Map.entry("BILL", 1),
            Map.entry("HIMS", 1), Map.entry("CYBER", 1), Map.entry("ZEN", 1), Map.entry("APR", 1), Map.entry("ZAMA", 1), Map.entry("KITE", 1),
            Map.entry("COW", 1), Map.entry("SIGN", 1), Map.entry("ICP", 1), Map.entry("GRASS", 1), Map.entry("WIF", 1), Map.entry("PROS", 1),
            Map.entry("ROBO", 1), Map.entry("OPN", 1), Map.entry("0G", 1), Map.entry("ROSE", 1), Map.entry("MYX", 1), Map.entry("CLO", 1),
            Map.entry("PUNDIAI", 1), Map.entry("LA", 1), Map.entry("TNSR", 1), Map.entry("BASED", 1), Map.entry("SPX", 1), Map.entry("UAI", 1),
            Map.entry("GUA", 1), Map.entry("H", 1), Map.entry("AZTEC", 1), Map.entry("DUSK", 1)
    );
}
